### ISSUE TITLE
Add 4 additional taxa to phenio

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#101]
These 4 taxa are used in monarch-kg, but aren't in phenio

```
NCBITaxon:44689
NCBITaxon:559292
NCBITaxon:8364
NCBITaxon:227321
```

**Comment by matentzn** [comment]
For a faster turnaround, in the future, you can add any taxon ids you like to https://github.com/monarch-initiative/phenio/blob/main/src/ontology/imports/ncbitaxon-taxslim_terms.txt

**Comment by matentzn** [comment]
Just make PR assign to me and it will show up with the next release!
