### ISSUE TITLE
404 not found https://github.com/monarch-initiative/phenio/releases/latest/download/phenio.owl

### ISSUE THREAD

**Issue by linikujp** [monarch-initiative/phenio#103]
### Describe the bug
When I clicke the link https://github.com/monarch-initiative/phenio/releases/latest/download/phenio.owl, it shows 404 not found.

**Comment by caufieldjh** [comment]
Thank you for catching that @linikujp - the link should now be https://github.com/monarch-initiative/phenio/releases/latest/download/phenio.owl.gz

I will fix the docs.
