### ISSUE TITLE
Add bridge axioms for EMAPA

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#34]
If `EMAPA` should be included then it should have corresponding bridge axioms to Uberon.

**Comment by caufieldjh** [comment]
This import is defined in the `phenio-odk.yaml`:
https://github.com/monarch-initiative/phenio/blob/main/src/ontology/phenio-odk.yaml#L36-L37

But it didn't make it into `phenio-edit.owl`.

**Comment by matentzn** [comment]
EMAPA same concerns as MA: not include and Monarch should map to Uberon.

**Comment by matentzn** [comment]
Fixed by #94
