### ISSUE TITLE
Biolink merge brings in LinkML types

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#37]
### Describe the bug

See https://github.com/monarch-initiative/monarch-ingest/issues/468#issuecomment-1564660130

Biolink imports linkml types (see https://github.com/biolink/biolink-model/blob/master/biolink-model.ttl) but these types remain in Phenio, hence they become nodes in KG-Phenio. 
They don't serve any purpose here.

**Comment by matentzn** [comment]
So how will you avoid them being nodes? the moment you say:

```
MONDO:123 bl:category bl:Disease
```

That moment `bl:Disease` will become a node, right?

**Comment by caufieldjh** [comment]
It does, and that's a separate (but related) issue - in this case it's that all children of bl:named_thing have slots with types defined by `linkml:types`, so we essentially need the base version of whatever a linkml schema is, except with all the roots for namespaces in Phenio like MONDO

**Comment by matentzn** [comment]
Maybe easier for now to just extract a filter module from the linkml schema, only including the exact terms that are in there, and only configuring certain properties to be included?
