### ISSUE TITLE
Consider adding MMO

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#38]
We have a lot of edges coming into the monarch graph with MMO evidence codes, and I'm wondering if we should consider adding MMO to Phenio.

**Comment by matentzn** [comment]
I am a bit conflicted, but will eventually agree with your request. My problem is that MMO is not a Monarch-vetted ontology, and it is not formally part of our metadata strategy. As far as I understand, the reasoning is that many sources we are ingesting are using MMO to record the type of study that led to the establishment of a gene to phenotype association (or any association, really). A measurement method though is something a bit different from an ECO evidence code, like "protein BLAST evidence used in manual assertion".

So before we go there, can you provide two or three examples, and point me to some writing that outlines the general evidence strategy we are implementing?

**Comment by sierra-moxon** [comment]
From what I remember of MOD/alliance data, MMO is primarily used for "assay type" in expression associations.
https://github.com/alliance-genome/agr_schemas/blob/111634ede67b3a710b636614ba517465a0d1c4c7/ingest/expression/wildtypeExpressionModelAnnotation.json#L33

```
{
  "assay": "MMO:0000655",
  "crossReference": {
    "id": "MGI:1203979",
    "pages": [
      "gene/expression/annotation/detail"
    ]
  },
  "dateAssigned": "2018-07-18T13:27:43-04:00",
  "evidence": {
    "crossReference": {
      "id": "MGI:1199209",
      "pages": [
        "reference"
      ]
    },
    "publicationId": "MGI:1199209"
  },
  "geneId": "MGI:99180",
  "whenExpressed": {
    "stageName": "TS23",
    "stageUberonSlimTerm": {
      "uberonTerm": "UBERON:0000068"
    }
  },
  "whereExpressed": {
    "anatomicalStructureTermId": "EMAPA:16039",
    "anatomicalStructureUberonSlimTermIds": [
      {
        "uberonTerm": "Other"
      }
    ],
    "whereExpressedStatement": "embryo"
  }
}
```

**Comment by caufieldjh** [comment]
Shouldn't be too difficult to add MMO, but as @matentzn mentions I'm curious about how we expect this to fit in with currently ingested relations. Are there particular reasons to include it in PHENIO vs directly into Monarch graph?

**Comment by kevinschaper** [comment]
Thanks @sierra-moxon, I should have taken a deeper look at the ingest, yeah, it doesn't seem like either assay or source values belong in has_evidence. 

I don't know if the answers to these questions are yes, but If I'm able to capture assay type (maybe `supporting study method type`?) and we want to show assays in the UI, then would it make sense to bring MMO into the phenio?

**Comment by matentzn** [comment]
@kevinschaper I think that would be a valid use case, but tbh, I would not push it (at least to show the label), in my view there is so much overlap here with MAXO and OBI that we should probably resolve the question first of which vocabulary we align towards.

**Comment by kevinschaper** [comment]
Sounds good - I'll close this out. I think the main thing to do is fix the ingest that is putting MMO in evidence.
