### ISSUE TITLE
FYPO terms missing

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#43]
It's possible that it's a kg-phenio bug, but it seems more likely that FYPO just isn't being included. It looks like the only FYPO term we're getting right now is `FYPO:0000001`

**Comment by matentzn** [comment]
Could be a PHENIO bug, but upheno2 certainly contains all of FYPO: https://ols.monarchinitiative.org/ontologies/upheno2/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFYPO_0000286

**Comment by caufieldjh** [comment]
AFAICT It's a PHENIO bug - Upheno2 contains FYPO and Upheno2 is included but FYPO is not: 
https://github.com/monarch-initiative/phenio/blob/417124fc09f85205d96bed7a61a3f7a943c89554/src/ontology/phenio-odk.yaml#L126C1-L135C45

**Comment by matentzn** [comment]
Easy fix then! Cool. Add to base iris!
