### ISSUE TITLE
Some questions about use cases?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/phenio#47]
I am reviewing the scope of the ontology needs of Monarch as a whole, and I have stumbled across a few ontologies whose use cases (in the Monarch App) are not well documented.

What are the use cases for:

- FAO
- STATO
- BFO
- CARO

@kevinschaper

**Comment by kevinschaper** [comment]
It looks like they're only used for associations that are contained within PHENIO, and not used directly by annotation associations:

|      category       | subject_namespace |      predicate      | object_namespace | provided_by  | count(*) |
|---------------------|-------------------|---------------------|------------------|--------------|----------|
| biolink:Association | BFO               | biolink:subclass_of | BFO              | phenio_edges | 34       |
| biolink:Association | BFO               | biolink:subclass_of | CHEBI            | phenio_edges | 1        |
| biolink:Association | BFO               | biolink:subclass_of | owl              | phenio_edges | 1        |
| biolink:Association | CHEBI             | biolink:subclass_of | BFO              | phenio_edges | 5        |
| biolink:Association | CL                | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | FAO               | biolink:related_to  | FAO              | phenio_edges | 27       |
| biolink:Association | FAO               | biolink:related_to  | NCBITaxon        | phenio_edges | 1        |
| biolink:Association | FAO               | biolink:subclass_of | FAO              | phenio_edges | 123      |
| biolink:Association | FBbt              | biolink:subclass_of | BFO              | phenio_edges | 35       |
| biolink:Association | FBbt              | biolink:subclass_of | CARO             | phenio_edges | 2        |
| biolink:Association | FYPO              | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | GO                | biolink:subclass_of | BFO              | phenio_edges | 6        |
| biolink:Association | IAO               | biolink:related_to  | BFO              | phenio_edges | 2        |
| biolink:Association | IAO               | biolink:related_to  | STATO            | phenio_edges | 1        |
| biolink:Association | IAO               | biolink:subclass_of | BFO              | phenio_edges | 2        |
| biolink:Association | MONDO             | biolink:subclass_of | BFO              | phenio_edges | 3        |
| biolink:Association | NCBITaxon         | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | OBI               | biolink:related_to  | BFO              | phenio_edges | 1        |
| biolink:Association | OBI               | biolink:related_to  | STATO            | phenio_edges | 4        |
| biolink:Association | OBI               | biolink:subclass_of | BFO              | phenio_edges | 6        |
| biolink:Association | OBI               | biolink:subclass_of | STATO            | phenio_edges | 2        |
| biolink:Association | OBO               | biolink:subclass_of | STATO            | phenio_edges | 2        |
| biolink:Association | OGMS              | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | PATO              | biolink:subclass_of | BFO              | phenio_edges | 2        |
| biolink:Association | PO                | biolink:subclass_of | BFO              | phenio_edges | 2        |
| biolink:Association | PR                | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | RO                | biolink:subclass_of | BFO              | phenio_edges | 2        |
| biolink:Association | SO                | biolink:subclass_of | BFO              | phenio_edges | 1        |
| biolink:Association | STATO             | biolink:related_to  | IAO              | phenio_edges | 5        |
| biolink:Association | STATO             | biolink:related_to  | OBI              | phenio_edges | 6        |
| biolink:Association | STATO             | biolink:related_to  | STATO            | phenio_edges | 23       |
| biolink:Association | STATO             | biolink:subclass_of | IAO              | phenio_edges | 11       |
| biolink:Association | STATO             | biolink:subclass_of | OBI              | phenio_edges | 11       |
| biolink:Association | STATO             | biolink:subclass_of | STATO            | phenio_edges | 12       |
| biolink:Association | UBERON            | biolink:subclass_of | BFO              | phenio_edges | 18       |
| biolink:Association | WBPhenotype       | biolink:related_to  | CARO             | phenio_edges | 6        |
| biolink:Association | WBbt              | biolink:subclass_of | BFO              | phenio_edges | 2797     |
| biolink:Association | ZP                | biolink:related_to  | CARO             | phenio_edges | 4        |

**Comment by matentzn** [comment]
Great. This is what I thought. I would motion to remove them from PHENIO then, if no one else complaints! Anyone we need to ask for permission?

**Comment by caufieldjh** [comment]
I'm happy to remove CARO, FAO and STATO, but BFO has a structural purpose in PHENIO due to being used as the root of UBERON, WBbt, FBBt, NCBITaxon, and a few others.
Unless we're moving toward rewiring everything to use a common root - which would be lovely!

**Comment by matentzn** [comment]
OK, I would suggest we start by removing these three. I will move the BFO question to a different issue.

**Comment by caufieldjh** [comment]
Addressed in #49
