### ISSUE TITLE
Stable URL for latest asset downloads

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#5]
We'll always want to just pull the latest phenio into monarch-ingest. I'm not sure if there's an existing pattern for how to implement this, but it might work to use a GitHub action like this to create a "latest" tag?

https://github.com/marketplace/actions/latest-tag#:~:text=Automatically%20creates%20%26%20updates%20a%20latest,need%20to%20use%20a%20branch

**Comment by caufieldjh** [comment]
Thanks for the suggestion! I'll just do it manually for now while releases are less frequent, so the most recent phenio.owl will be at https://github.com/monarch-initiative/phenio/releases/latest/download/phenio.owl

Note that the above link works *whether I tag it as latest or not* - that will just give you the literal latest version of the specified file.
