### ISSUE TITLE
biolink-model.owl.ttl is moving in biolink 4.0.0

### ISSUE THREAD

**Issue by sierra-moxon** [monarch-initiative/phenio#50]
Please note: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl will no longer be available at this path in biolink 4.0.0.

Instead, it will be here: https://raw.githubusercontent.com/biolink/biolink-model/master/project/owl/biolink_model.owl.ttl

or via w3id here (this is still the same path/URI as pre-4.0.0): https://w3id.org/biolink/biolink-model.owl.ttl

https://github.com/monarch-initiative/phenio/blob/f410ad4fd171f15dd07307fd28b564aba7835738/src/ontology/phenio.Makefile#L6

**Comment by caufieldjh** [comment]
Thanks for the heads up @sierra-moxon !
