### ISSUE TITLE
Add DDPHENO

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#55]
Monarch-kg is has a dictyBase G2P ingest, but we haven't yet added the DDPHENO ontology to PHENIO, so let's bring it in. 

Linked to https://github.com/monarch-initiative/monarch-app/issues/551

**Comment by matentzn** [comment]
@caufieldjh when you add DDPHENO to the base iris, hold of a minute with a release as some important changes are coming in from uPheno (cc @udp to let Harry now when release is done)

**Comment by sagehrke** [comment]
@caufieldjh do you have any updates on this? Thank you!

**Comment by caufieldjh** [comment]
No updates on this - will focus on it once #59 is complete.

**Comment by caufieldjh** [comment]
@matentzn Should we expect there to be any uberon bridges to DDPHENO? Do we want/need DDANAT?
