### ISSUE TITLE
Investigate missing MONDO xrefs

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#67]
### Describe the bug

In reference to https://github.com/monarch-initiative/monarch-app/issues/652 -
MONDO identifiers don't appear to have their corresponding OMIM IDs, or at least they don't end up in the Monarch KG.
They may go missing here or in KG-Phenio.

**Comment by matentzn** [comment]
Let me know what you find out. I would like to suggest that we should prefer the skos matches for populating the search index, but we will anyways drop all non-exact xrefs in future releases of Mondo, which means that the effect is the same.

**Comment by caufieldjh** [comment]
OK, it looks like MONDO classes still have their corresponding OMIM `oboInOwl:hasDbXref` and `skos:exactMatch` in `phenio.owl`, at least as of the most recent release (03-13-24).

Example for MONDO:0026765, the ID in the linked monarch-app issue:
```owl
<rdf:Description rdf:about="http://purl.obolibrary.org/obo/MONDO_0026765">
        <obo:IAO_0000233 rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://github.com/monarch-initiative/mondo/issues/4521</obo:IAO_0000233>
        <oboInOwl:hasDbXref>OMIM:301045</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym>congenital disorder of glycosylation, type IIr, X-linked recessive</oboInOwl:hasExactSynonym>
        <oboInOwl:hasRelatedSynonym>CDG IIr</oboInOwl:hasRelatedSynonym>
        <oboInOwl:hasRelatedSynonym>CDG2R</oboInOwl:hasRelatedSynonym>
        <oboInOwl:hasRelatedSynonym>CONGENITAL DISORDER OF GLYCOSYLATION, TYPE IIr</oboInOwl:hasRelatedSynonym>
        <oboInOwl:id>MONDO:0026765</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#inferred_rare"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#rare"/>
        <rdfs:label>congenital disorder of glycosylation, type IIr</rdfs:label>
        <skos:exactMatch rdf:resource="https://omim.org/entry/301045"/>
    </rdf:Description>
```

I'm assuming that the linked issue here (https://github.com/monarch-initiative/mondo/issues/4521) is unrelated as it's about name discrepancies and the map is still defined here as expected.

**Comment by caufieldjh** [comment]
Will look in KG-Phenio next.
