### ISSUE TITLE
Latest phenio doesn't include relation-graph tsv 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/phenio#69]
The new release only went up 6 hours ago, so maybe it's something that gets updated in the build later, but I happened to try to download https://github.com/monarch-initiative/phenio/releases/latest/download/phenio-relation-graph.tar.gz and found that it wasn't there.

**Comment by matentzn** [comment]
Weird that this URL redirected to an incomplete release (it was still uploading).

Check again: https://github.com/monarch-initiative/phenio/releases/tag/v2024-04-25

**Comment by kevinschaper** [comment]
Whoa! That’s good to know about.
