### ISSUE TITLE
Move preprocessing steps from KG-Phenio to here

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#7]
This PR (https://github.com/Knowledge-Graph-Hub/kg-phenio/pull/43) added ROBOT preprocessing to phenio to make it more KG-friendly, but we'd like all the results to be part of the standard `phenio.owl` releases.
Move the processing here.

**Comment by caufieldjh** [comment]
And in KG-Phenio, consider using a Koza ingest as the preprocessing to ensure Biolink adherence, CURIEs, etc

**Comment by matentzn** [comment]
I agree. Good move!
