### ISSUE TITLE
Include Biolink categories for relations

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#70]
The current process for adding Biolink categories to classes looks like this in the Makefile:
https://github.com/monarch-initiative/phenio/blob/7e882424dde9f2a057904b671c56a90239801913/src/ontology/phenio.Makefile#L33C1-L41C44

and that uses this query:
https://github.com/monarch-initiative/phenio/blob/7e882424dde9f2a057904b671c56a90239801913/src/sparql/bl-categories.ru#L11C1-L26C2

Can we replicate that process for relations?
See https://github.com/monarch-initiative/monarch-app/issues/684

See also #37 , #32 , #22

**Comment by matentzn** [comment]
As long as I think KGX works the way it does, it should be easy. Instead of `INSERT`ing a triple, you insert a reified statement with a biolink assertion on it. Let me know if you need help.

**Comment by matentzn** [comment]
@caufieldjh will we still do this?

**Comment by caufieldjh** [comment]
Nope!
If it's done in KG-Phenio then it doesn't need to happen here.
