### ISSUE TITLE
OBA terms aren't getting names

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#79]
### Describe the bug

UPHENO uses OBA, and PHENIO imports both (UPHENO and OBA), but ~5984 OBA terms have blank labels.

Does the OBA owl have labels for each class?

How can we get labels on the OBA terms?

### Version

Current as of build 2024-06-06

**Comment by matentzn** [comment]
https://github.com/monarch-initiative/phenio/blob/29ecf3d7351867d1f34c6e337a42b45bf3c94018/src/ontology/phenio-odk.yaml#L20

😱

**Comment by caufieldjh** [comment]
Oh no. Do you remember why OBA Is excluded there?

**Comment by matentzn** [comment]
Historical, should 100% not be there.
