### ISSUE TITLE
Add MAXO

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/phenio#88]
### Describe the desired behavior or enhancement

@kevinschaper requests addition of MAXO.

https://www.ebi.ac.uk/ols4/ontologies/maxo

### Additional context

Note that MAXO has >20 imports, many of which are in PHENIO already, so this will need to be the base.

**Comment by matentzn** [comment]
I agree with this, we should do this soon. @kevinschaper are we thinking about importing MAXO annotations into Monarch KG at all?

**Comment by kevinschaper** [comment]
Yeah, in progress here: https://github.com/monarch-initiative/maxo-annotation-ingest

I was hoping to at least get an initial version of this ingest into the KG for the Nov release.

**Comment by matentzn** [comment]
I guess it would be good then to have MAXO in phenio so you can at least get the labels correctly, right?

**Comment by kevinschaper** [comment]
Yup! If I add the ingest ahead of having MAXO nodes in Phenio, the edges would end up getting dropped. I could technically create nodes from the IDs and labels in the MAXO annotations if I just want a node with a label and category on the other side of the association, but if we did that sort of nonsense we wouldn't be the ontology people! :smile:

It's not a hard requirement to get MAXO into Phenio in the next few days though, so if we get bumped until December, that's ok.

**Comment by matentzn** [comment]
@caufieldjh can you are shall i do it? either way fine by me!

**Comment by caufieldjh** [comment]
I'll take care of this. Building a version now with the most recent Upheno and Mondo, so if that works as expected then next step will be adding MAXO.

**Comment by matentzn** [comment]
Fixed by #94 

Sorry @caufieldjh I know this was against your orders but I would have had to jump through some unnecessary hoops if I didn't do it all in one wash.

**Comment by caufieldjh** [comment]
OK, no worries
