### ISSUE TITLE
Make it easy to select the correct phenio version for a given Monarch KG

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/phenio#95]

**Comment by matentzn** [comment]
@kevinschaper what is the easiest way to figure out which version of phenio was used in a given Monarch KG?

**Comment by kevinschaper** [comment]
This could end up being wrong if a release happens between the download job and kg build job, I think, but we capture the latest phenio that exists when the kg is built here https://data.monarchinitiative.org/monarch-kg-dev/latest/metadata.yaml 

(We really need to get the versioning into the core of the build)

**Comment by matentzn** [comment]
Perfect thank you! That is good enough!! For me now!
